import type { Job, Toolpath, MachineProfile, Tool } from '@cool-cam/core';
import { MACHINES, SHAPEOKO_HDM, getTool, estimate, formatDuration, stockBounds } from '@cool-cam/core';
import { fitArcs } from './arcs.js';

export interface PostOptions {
  /** Override the machine's tool-change style. */
  toolChange?: MachineProfile['toolChange'];
  /** Emit a spindle spin-up dwell after M3. */
  spindleDwell?: boolean;
  /** Decimal places for coordinates. */
  precision?: number;
  /** Return to X0 Y0 at the end (after raising to safe Z). */
  parkAtOrigin?: boolean;
  /** Emit line numbers. */
  lineNumbers?: boolean;
  /** Include per-move kind comments (verbose). */
  annotate?: boolean;
  /** Fit G2/G3 arcs over circular runs (default true). */
  arcs?: boolean;
  /** Arc fitting tolerance, mm (default 0.01). */
  arcTolerance?: number;
}

export interface PostResult {
  gcode: string;
  lines: number;
  toolChanges: number;
  seconds: number;
  warnings: string[];
  /** Number of G2/G3 arcs emitted. */
  arcs: number;
}

/**
 * GRBL post tuned for Carbide Motion + BitSetter on a Shapeoko HDM.
 * - Absolute mm, G17/G94, G54.
 * - Every tool (including the first) is introduced with `M6 T<n>` so Carbide Motion prompts and probes the BitSetter.
 * - Before each tool change and at the end, Z is raised in machine coordinates (G53) so the BitSetter move is safe.
 * - No canned cycles or cutter compensation (GRBL 1.1 does not support them); pecks and offsets are already expanded.
 */
export function postGrbl(job: Job, toolpaths: Toolpath[], opts: PostOptions = {}): PostResult {
  const machine = MACHINES[job.machineId] ?? SHAPEOKO_HDM;
  const p = opts.precision ?? 3;
  const toolChange = opts.toolChange ?? machine.toolChange;
  const warnings: string[] = [];
  const out: string[] = [];
  let n = 0;
  const emit = (s: string) => { out.push(opts.lineNumbers ? `N${(++n) * 10} ${s}` : s); };
  const fmt = (v: number) => { const s = v.toFixed(p); return s === '-0.000' || /^-0\.0+$/.test(s) ? s.slice(1) : s; };

  const b = stockBounds(job.stock);
  const usedTools = new Map<string, Tool>();
  for (const tp of toolpaths) if (tp.moves.length) usedTools.set(tp.toolId, getTool(job, tp.toolId));
  let seconds = 0;

  emit(`(${job.name})`);
  emit(`(Generated by Cool CAM for ${machine.name})`);
  emit(`(Stock: ${job.stock.width} x ${job.stock.length} x ${job.stock.thickness} mm, origin ${job.stock.origin}, Z0 at stock ${job.stock.zOrigin})`);
  if (job.material) emit(`(Material: ${job.material})`);
  for (const t of usedTools.values()) emit(`(T${t.number} = ${t.name})`);
  emit('G90 G21 G17 G94');
  emit('G54');

  let curTool: string | null = null;
  let curF: number | null = null;
  let cx = NaN, cy = NaN, cz = NaN;
  let toolChanges = 0; let arcCount = 0;
  let spindleOn = false;

  const safeUp = () => { emit(`G53 G0 Z${fmt(machine.safeZMachine)}`); cz = NaN; };

  for (const tp of toolpaths) {
    if (!tp.moves.length) continue;
    const tool = getTool(job, tp.toolId);
    emit('');
    emit(`(Operation: ${tp.opName})`);
    if (tp.toolId !== curTool) {
      if (spindleOn) { emit('M5'); spindleOn = false; }
      safeUp();
      switch (toolChange) {
        case 'm6-prompt': emit(`M6 T${tool.number}`); break;
        case 'm0-pause': emit(`(Tool change: T${tool.number} ${tool.name})`); emit(`T${tool.number}`); emit('M0'); break;
        case 'none': emit(`(Tool: T${tool.number} ${tool.name})`); break;
      }
      curTool = tp.toolId; toolChanges++;
      const rpm = Math.round(tp.rpm);
      if (rpm < machine.spindle.minRpm || rpm > machine.spindle.maxRpm) warnings.push(`${tp.opName}: ${rpm} rpm is outside the spindle range ${machine.spindle.minRpm}-${machine.spindle.maxRpm}.`);
      emit(`M3 S${rpm}`);
      if (opts.spindleDwell !== false) emit(`G4 P${machine.spindle.spinUpSeconds}`);
      spindleOn = true;
      curF = null;
    }
    const startZ = b.top + job.safeZ;
    seconds += estimate(tp, machine, { kind: 'rapid', x: isNaN(cx) ? 0 : cx, y: isNaN(cy) ? 0 : cy, z: isNaN(cz) ? startZ : cz }).seconds;
    const segments = opts.arcs === false ? tp.moves.map(m => ({ kind: 'line' as const, m })) : fitArcs(tp.moves, { kind: 'rapid', x: isNaN(cx) ? 0 : cx, y: isNaN(cy) ? 0 : cy, z: isNaN(cz) ? startZ : cz }, opts.arcTolerance ?? 0.01);
    for (const seg of segments) {
      const m = seg.m;
      if (seg.kind === 'arc') {
        const f = Math.round(m.f ?? 1000); const fw = f !== curF ? ` F${f}` : ''; curF = f;
        emit(`${seg.cw ? 'G2' : 'G3'} X${fmt(m.x)} Y${fmt(m.y)} I${fmt(seg.cx - cx)} J${fmt(seg.cy - cy)}${fw}`);
        cx = m.x; cy = m.y; cz = m.z; arcCount++; continue;
      }
      const words: string[] = [];
      if (Math.abs(m.x - cx) > 5e-4 || isNaN(cx)) words.push(`X${fmt(m.x)}`);
      if (Math.abs(m.y - cy) > 5e-4 || isNaN(cy)) words.push(`Y${fmt(m.y)}`);
      if (Math.abs(m.z - cz) > 5e-4 || isNaN(cz)) words.push(`Z${fmt(m.z)}`);
      if (words.length === 0) continue;
      if (m.kind === 'rapid' || m.kind === 'retract') {
        // Split combined XY+Z rapids: descend after traversing, ascend before traversing.
        const xy = words.filter(w => !w.startsWith('Z')); const zw = words.find(w => w.startsWith('Z'));
        if (xy.length && zw && !isNaN(cz)) {
          if (m.z < cz) { emit(`G0 ${xy.join(' ')}`); emit(`G0 ${zw}`); }
          else { emit(`G0 ${zw}`); emit(`G0 ${xy.join(' ')}`); }
        } else if (xy.length && zw) { emit(`G0 ${zw}`); emit(`G0 ${xy.join(' ')}`); }
        else emit(`G0 ${words.join(' ')}`);
      } else {
        const f = Math.round(m.f ?? 1000);
        if (f !== curF) { words.push(`F${f}`); curF = f; }
        emit(`G1 ${words.join(' ')}${opts.annotate ? ` (${m.kind})` : ''}`);
      }
      cx = m.x; cy = m.y; cz = m.z;
      if (m.x < b.x0 - 200 || m.x > b.x1 + 200 || m.y < b.y0 - 200 || m.y > b.y1 + 200) {
        /* far outside the stock: flag once */
        if (!warnings.some(w => w.startsWith('Moves far outside'))) warnings.push('Moves far outside the stock detected; check shape placement.');
      }
    }
  }
  emit('');
  if (spindleOn) emit('M5');
  safeUp();
  if (opts.parkAtOrigin) emit('G0 X0 Y0');
  emit('M30');
  const gcode = out.join('\n') + '\n';
  return { gcode, lines: out.length, toolChanges, seconds, warnings, arcs: arcCount };
}

export function summarizePost(r: PostResult): string {
  return `${r.lines} lines (${r.arcs} arcs), ${r.toolChanges} tool change(s), est. ${formatDuration(r.seconds)}${r.warnings.length ? `, warnings: ${r.warnings.join(' | ')}` : ''}`;
}
